* Bug notes
  - New bugs are added to the bottom.
  - Bug reports (will eventually) be prefaced like this
    1. * Descriptive name
    2.   - description of behavior
    3.   - date found
    4.   - name of reporter
    5.   - paste example of behavior

* mysterious remove error
  - Actually, I have no idea why this happened yet.
  - found some time ago TODO check github for date
  - Garrett Fuller
** pasted
        y or n: y

	Welcome to tic-tac-toe!.

	Let's flip a coin to see who goes first

	Heads or tails? h or t: t

	The coin landed on tails.

	You are going first.

	Here is the game board.

	  a   b   c
	1   |   |
	  ==|===|==
	2   |   |
	  ==|===|==
	3   |   |

	It is your turn to move.

	Enter your move. eg. 1a or 3c: 2b

	  a   b   c
	1   |   |
	  ==|===|==
	2   | X |
	  ==|===|==
	3   |   |

	It is the computer turn.

	  a   b   c
	1 O |   |
	  ==|===|==
	2   | X |
	  ==|===|==
	3   |   |

	It is your turn to move.

	Enter your move. eg. 1a or 3c: 3c

	  a   b   c
	1 O |   |
	  ==|===|==
	2   | X |
	  ==|===|==
	3   |   | X

	It is the computer turn.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mint/documents/prog/tictactoe/tictac_game.py", line 359, in <module>
    main()
  File "/home/mint/documents/prog/tictactoe/tictac_game.py", line 315, in main
    move = computer_move(gaming)
  File "/home/mint/documents/prog/tictactoe/tictac_game.py", line 155, in computer_move
    availableMoves.remove(move)
ValueError: list.remove(x): x not in list
>>>

* Second player can play to win!?
  - same as name
  - TODO check github for date added
  - Garrett Fuller
** Pasted example
	Here is the game board.

	  a   b   c
	1   |   |
	  ==|===|==
	2   |   |
	  ==|===|==
	3   |   |

	  a   b   c
	1   |   |
	  ==|===|==
	2   |   |
	  ==|===|==
	3 X |   |

	It is your turn to move.

	Enter your move. eg. 1a or 3c: 2a

	  a   b   c
	1   |   |
	  ==|===|==
	2 O |   |
	  ==|===|==
	3 X |   |

	It is the computer turn.

	  a   b   c
	1   |   |
	  ==|===|==
	2 O |   |
	  ==|===|==
	3 X |   | X

	It is your turn to move.

	Enter your move. eg. 1a or 3c: 3b

	  a   b   c
	1   |   |
	  ==|===|==
	2 O |   |
	  ==|===|==
	3 X | O | X

	It is the computer turn.

	  a   b   c
	1 X |   |
	  ==|===|==
	2 O |   |
	  ==|===|==
	3 X | O | X

	It is your turn to move.

	Enter your move. eg. 1a or 3c: 2b

	  a   b   c
	1 X |   |
	  ==|===|==
	2 O | O |
	  ==|===|==
	3 X | O | X

	It is the computer turn.

	  a   b   c
	1 X |   |
	  ==|===|==
	2 O | O | X
	  ==|===|==
	3 X | O | X

	It is your turn to move.

	Enter your move. eg. 1a or 3c: 1a


	That is not a legal move.


	Enter your move. eg. 1a or 3c: 1b

	  a   b   c
	1 X | O |
	  ==|===|==
	2 O | O | X
	  ==|===|==
	3 X | O | X

	The  O 's have won the game!

	Would you like to play again? :)

	y or n: n

	Thanks a whole lot for playing!
>>>


* Computer blocks and fails to take winning move.
  - The name AND it's a tie prints inappropriately
  - May 20 2015
  - Garrett Fuller
** Paste example
   	Welcome to tic-tac-toe!.

	Let's flip a coin to see who goes first

	Heads or tails? h or t: h

	The coin landed on heads.

	You are going first.

	Here is the game board.

	  a   b   c
	1   |   |
	  ==|===|==
	2   |   |
	  ==|===|==
	3   |   |

	It is your turn to move.

	Enter your move. eg. 1a or 3c: 11


	That is not a legal move.


	Enter your move. eg. 1a or 3c: 1a

	  a   b   c
	1 X |   |
	  ==|===|==
	2   |   |
	  ==|===|==
	3   |   |

	It is the computer turn.

	  a   b   c
	1 X |   | O
	  ==|===|==
	2   |   |
	  ==|===|==
	3   |   |

	It is your turn to move.

	Enter your move. eg. 1a or 3c: 2a

	  a   b   c
	1 X |   | O
	  ==|===|==
	2 X |   |
	  ==|===|==
	3   |   |

	It is the computer turn.

	  a   b   c
	1 X |   | O
	  ==|===|==
	2 X |   |
	  ==|===|==
	3 O |   |

	It is your turn to move.

	Enter your move. eg. 1a or 3c: 2b

	  a   b   c
	1 X |   | O
	  ==|===|==
	2 X | X |
	  ==|===|==
	3 O |   |

	It is the computer turn.

	  a   b   c
	1 X |   | O
	  ==|===|==
	2 X | X | O
	  ==|===|==
	3 O |   |

	It is your turn to move.

	Enter your move. eg. 1a or 3c: 3b

	  a   b   c
	1 X |   | O
	  ==|===|==
	2 X | X | O
	  ==|===|==
	3 O | X |

	It is the computer turn.

	  a   b   c
	1 X | O | O
	  ==|===|==
	2 X | X | O
	  ==|===|==
	3 O | X |

	It is your turn to move.

	Enter your move. eg. 1a or 3c: 3c

	  a   b   c
	1 X | O | O
	  ==|===|==
	2 X | X | O
	  ==|===|==
	3 O | X | X

	The  X 's have won the game!

	It's a TIE!

	Would you like to play again? :)
